apiVersion: v1
kind: Service
metadata:
  name: oo4u
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "oo4u"
    port: 8080
  selector:
    app: oo4u
